### ISSUE TITLE
什么时候出一个mac版本的

### ISSUE THREAD

**Issue by AlanPaine** [flytkgl/PDFQFZ#37]
什么时候出一个mac版本的

**Comment by zarrichen** [comment]
同问，可否安排个mac的

**Comment by flytkgl** [comment]
这个并没有计划哦

**Comment by btwise** [comment]
> 什么时候出一个 mac 版本的

已经实现macos和linux版本，有需要私信联系

**Comment by btwise** [comment]
> 同问，可否安排个mac的

已经实现macos和linux版本，有需要私信联系

**Comment by fieri** [comment]
@btwise 安卓版本的有吗

**Comment by btwise** [comment]
正在制作WEB版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年2月21日(周五) 晚上6:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [flytkgl/PDFQFZ] 什么时候出一个mac版本的 (Issue #37)


   
@btwise 安卓版本的有吗

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
  fieri left a comment (flytkgl/PDFQFZ#37)
 
@btwise 安卓版本的有吗
